version: '3'
services:
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: suggestion-api
    links:
      - redis-server
    ports:
      - "8080:8080"