version: '3.8'
services:
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
  app:
    image: riccardo006/suggestion-api:latest
    container_name: suggestion-api
    links:
      - redis-server
    ports:
      - "80:8080"