version: '3.8'
services:
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
  app:
    build: .
    image: suggestion-api
    container_name: suggestion-api
    links:
      - redis-server
    ports:
      - "8080:8080"