version: '3.8'
services:
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - suggestion-api-network
  app:
    image: riccardo006/suggestion-api:latest
    container_name: suggestion-api
    links:
      - redis-server
    ports:
      - "80:8080"
    depends_on:
      - redis-server
    networks:
      - suggestion-api-network

networks:
  suggestion-api-network:
    driver: bridge