name: suggestion-api-cicd

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to respository
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action/@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Build docker image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/suggestion-api:latest
      
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd suggestion-api
             curl -o docker-compose.yml https://raw.githubusercontent.com/shirloin/suggestion-api/main/docker-compose.yml
             docker pull ${{secrets.DOCKERHUB_USERNAME}}/suggestion-api:latest
             docker compose up -d