name: suggestion-api-cicd

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Checkout to respository
      uses: actions/checkout@v3

      name: Login to docker hub
      uses: docker/login-action/@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      name: Build docker image and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/suggestion-api:latest
      
      name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE-USER: ubuntu
        SERVER-IP: ${{secrets.SERVER_IP}}
        REMOTE-PATH: /home/ubuntu/suggestion-api
        LOCAL-PATH: ./
